In [237]:
# initial setup
try:
    # settings colab:
    import google.colab
        
except ModuleNotFoundError:    
    # settings local:
    %run "../../../common/0_notebooks_base_setup.py"

pandas=1.0.3 already installed
matplotlib=2.2.2 already installed
bokeh=2.0.0 already installed
seaborn=0.10.0 already installed

In [238]:
import pandas as pd
import seaborn as sns
import re
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import chart_studio
import chart_studio.plotly as py
import unidecode as ud

In [239]:
pd.set_option('display.max_rows', 300)
pd.set_option('display.width', 5000)

In [240]:
import chardet
def get_encoding_type(csv_path):
    rawdata = open(csv_path, 'rb').read()
    result = chardet.detect(rawdata)
    return result.get('encoding')

In [245]:
data = pd.read_csv("properati.csv", encoding="iso-8859-1")

In [246]:
#Creo una copia del DF
data_clean = data.copy(deep=True)

In [247]:
#Columnas que son string
columnas_str = ['operation', 'property_type', 'place_name', 'place_with_parent_names', 'country_name', 'state_name', 'description', 'title']

In [248]:
#Le quito los espacios en blanco
for columna in columnas_str:
    data_clean[columna] = data_clean[columna].str.strip()

<span style="font-size:24px">OPERACION<span>

In [249]:
#BUSCAR NULOS
data_clean["property_type"].isnull().sum()

0

In [250]:
#Expresión regular para buscar venta o alquiler
regex = re.compile("(venta)|(alquiler)", flags = re.IGNORECASE)

In [252]:
#Buscar Venta o Alquiler en description
regexOperacionesDescription = data_clean.description.apply(lambda x: regex.search(str(x)))
dfVentasDescription = regexOperacionesDescription.apply(lambda x: np.NaN if x is None else x.group(0))

#Normalizar
dfVentasDescription[dfVentasDescription.notnull()].unique()
dfVentasDescription.replace(["VENTA", "venta"], "Venta", inplace=True)
dfVentasDescription.replace(["alquiler", "ALQUILER"], "Alquiler", inplace=True)
dfVentasDescription[dfVentasDescription.notnull()].unique()

#Crear columna Operacion
data_clean["Operacion_Description"] = dfVentasDescription
data_clean["Operacion_Description"].value_counts()

Venta       42336
Alquiler     1325
Name: Operacion_Description, dtype: int64

In [253]:
#Buscar Venta o Alquiler en title
regexOperacionesTitle = data_clean.title.apply(lambda x: regex.search(str(x)))
dfVentasTitle = regexOperacionesTitle.apply(lambda x: np.NaN if x is None else x.group(0))

#Normalizar
dfVentasTitle[dfVentasTitle.notnull()].unique()
dfVentasTitle.replace(["VENTA", "venta"], "Venta", inplace=True)
dfVentasTitle.replace(["alquiler", "ALQUILER"], "Alquiler", inplace=True)
dfVentasTitle[dfVentasTitle.notnull()].unique()

#Crear columna Title
data_clean["Operacion_Title"] = dfVentasTitle
data_clean["Operacion_Title"].value_counts()

Venta       36125
Alquiler      217
Name: Operacion_Title, dtype: int64

In [254]:
#Buscar Venta o Alquiler en properati_url
regexOperacionesURL = data_clean.properati_url.apply(lambda x: regex.search(str(x)))
dfVentasURL = regexOperacionesURL.apply(lambda x: np.NaN if x is None else x.group(0))

#Normalizar
dfVentasURL[dfVentasURL.notnull()].unique()
dfVentasURL.replace(["VENTA", "venta"], "Venta", inplace=True)
dfVentasURL.replace(["alquiler", "ALQUILER"], "Alquiler", inplace=True)
dfVentasURL[dfVentasURL.notnull()].unique()

#Crear columna URL
data_clean["Operacion_URL"] = dfVentasURL
data_clean["Operacion_URL"].value_counts()

Venta       121086
Alquiler       134
Name: Operacion_URL, dtype: int64

In [257]:
#Crear la columna Operacion con Operacion_URL que contempla todos los casos
data_clean["Operacion"] = data_clean["Operacion_URL"]

In [359]:
#Precios mínimos y máximos para alquiler
data_clean[data_clean.price_aprox_usd > 0].filter(items=["property_type", "price_aprox_usd"]).groupby(by="property_type").agg(['min', 'max'])

              price_aprox_usd
                          min         max
property_type
PH                    5047.53   2800000.0
apartment             4666.62  46545445.0
house                 5047.53  25000000.0
store                 4952.45  13000000.0

In [360]:
#Revisar los casos con precios menores a 10.000 para ver que no sean alquileres
data_clean[(data_clean.property_type == "PH") & (data_clean.price_aprox_usd < 10000)].filter(items=["price_aprox_usd", "description"])

        price_aprox_usd                                        description
36433           5047.53  CODIGO:  ubicado en: Guemes 4200 -  Publicado ...
49105           6617.87  CODIGO: 3 ubicado en: IbaÃ±ez 7400 -  Publicad...
62524           6169.20  CODIGO: 683-1295 ubicado en: Ezeiza NÂ° 2960 1...
116277          5327.94  P3 ambientes, posee: Living comedor, cocina co...

In [361]:
#Revisar los casos con precios menores a 10.000 para ver que no sean alquileres
data_clean[(data_clean.property_type == "home") & (data_clean.price_aprox_usd < 10000)].filter(items=["price_aprox_usd", "description"])

Empty DataFrame
Columns: [price_aprox_usd, description]
Index: []

In [362]:
#Revisar los casos con precios menores a 10.000 para ver que no sean alquileres
data_clean[(data_clean.property_type == "apartment") & (data_clean.price_aprox_usd < 10000)].filter(items=["price_aprox_usd", "description"])

        price_aprox_usd                                        description
4399            5000.00  Corredor Responsable: Mauro Marvisi - CMCPSI 5...
6720            5608.31  BV Rondeau / Nancen: A metros del Shoping Port...
17731           5608.36  CODIGO:  ubicado en: COOPERATIVA DE VIVIENDA R...
18705           5608.36  CODIGO: 85 ubicado en: mitre 100 -  Publicado ...
19336           7851.71  Departamento de dos dormitorios con placard en...
20133           5103.61  CODIGO: 6375 ubicado en: Vera 1100 -  Publicad...
21197           7583.27  SE OFRECE DEPARTAMENTO DE 2 DORMITORIOS EN BAR...
23142           7963.88  Corredor Responsable: Mariana Carrizo - CPCPI:...
23307           8973.38  Corredor Responsable: Caroline Hogner - CCI St...
26931           9500.00  Excelente Metros de Subte Lnea *A*  Frente Sup...
26932           9500.00  Excelente Metros de Subte L?nea *A*  Frente Su...
26933           9500.00  Excelente Metros de Subte L?nea *A*  Frente Su...
27265           5047.53  Corredor Responsable: Jesica Tobio - CI Mat. N...
27823           7851.71  Dpto en venta en Fincas de Iraola IIBalcon con...
27946           6842.20  Corredor Responsable: Marcos Provvidenti - CCI...
32900           7290.87  CODIGO: 2062-653 ubicado en: PLAN DE COOPERATI...
34666           4666.62  PLAN BAUEN PILAY 1 DORMITORIO SIN ADJUDICAR CO...
37172           7851.71  CODIGO:  ubicado en: 9 de julio 1100 -  Public...
41810           7800.00  Vendo plan de vivienda. Departamento sin adjud...
41843           7290.87  Vendo plan de vivienda. Departamento sin adjud...
41846           5608.36  Plan Edificios de Macrocentro--- Departamento ...
41867           6000.00  Plan Edificios de Macrocentro--- Departamento ...
41946           7010.45  Excelente departamento ubicado en Nueva Cordob...
43853           7466.60  DescripciÃÂ³n: Departamento en impecable esta...
46157           9253.80  FEIGELMULLER ESTUDIO INMOBILIARIO 4963527 9 A ...
46378           6231.51  Departamentos en construcciÃ³n sobre Boulevard...
46917           5608.36  Plan Edificios de Macrocentro--- Departamento ...
46918           7290.87  Vendo plan de vivienda. Departamento sin adjud...
49104           5552.28  CODIGO: 633-1434 ubicado en: Talcahuano 16 -  ...
49852           7290.87  DEPARTAMENTO 3 AMBIENTES ONCEFrente con balcÃ³...
51602           5440.11  2 ambientes amplios, Living comedor, dormitori...
52421           5000.00  Corredor Responsable: Mauro Marvisi - CMCPSI 5...
52424           6000.00  Corredor Responsable: Mauro Marvisi - CMCPSI 5...
52725           9422.05  Disponemos de este departamento de 3 ambientes...
53678           5191.62  DUEÃO VENDE 2amb C/amplio Patio\t\t* Amplio d...
54536           5327.94  Apto profesional. Apto crÃ©dito. Departamento ...
55108           7290.87  3 amb con dependencia de servicio y baÃ±o. 2 d...
55686           6730.04  CODIGO: 512-1778 ubicado en: RAMON FALCON 2353...
57415           5047.53  San Fernando: departamento de  dos ambientes e...
58825           6393.53  Excelente departamento en planta baja de dos a...
58958           7010.45  CODIGO: 3407-ara2751 ubicado en: Mariano Alegr...
59881           9916.58  Se vende plan de departamento de 3 dormitorios...
62480           6231.51  CODIGO: 1818-v152 ubicado en: Costanera 1020 -...
70951           5608.36  Departamento con Electricidad, NeuquÃ©n, Confl...
70976           5608.36  Departamento con Agua Corriente, NeuquÃ©n, Con...
70989           5608.36  Departamento con Electricidad, NeuquÃ©n, Confl...
71005           5608.36  Departamento con Electricidad, NeuquÃ©n, Confl...
71023           5608.36  Departamento con Electricidad, NeuquÃ©n, Confl...
71043           5608.36  Departamento con Electricidad, NeuquÃ©n, Confl...
76101           6169.20  Departamento de 3 ambientes, todo luz y sol!. ...
87402           7571.29  Unidad: "16" ULTIMO departamento de 2 dormitor...
87611           6348.67  Departamento de 1 dormitorio en Cnel Olmedo Co...
99272           5327.94  Loteo de Generosas Dimensiones desde los 400 m...
99519           7178.71  Departamento en venta de dos ambientes en Cole...
102031          5047.53  Excelente departamento en pleno corazÃ³n de la...
106677          8126.52  Sergio Villella Inmobiliaria, presenta departa...
108145          5103.61  CODIGO: 916-69637 ubicado en: SCALABRINI ORTIZ...
111505          8132.13  CODIGO: 735-Uriburu ubicado en: Uriburu 535 - ...
112382          8029.33  Duit Propiedades presenta Ignea 12, ubicado en...
113642          6730.04  CODIGO:  ubicado en: Yrigoyen 1100 -  Publicad...
113692          5159.69  CODIGO:  ubicado en: Espora 900 -  Publicado p...
114157          5500.00  DEPARTAMENTOS DE CATEGORIA: 3 ambientes de 76....
114444          8861.22  Depto. con vista a la nueva peatonal de la cal...
115181          7290.87  2 PISO CONTRA FRENTEÂ Living- comedor amplioÂ ...
115223          9814.64  Liquido plan de depto de 1 dormitorio con coch...
115717          9534.22  3d + dep. 3b liv/com coc/comÂ Calef. x rad. Ba...
119958          7571.29  CODIGO: 3410-238 ubicado en: Avenida Jujuy 300...

In [363]:
#Revisar los casos con precios menores a 10.000 para ver que no sean alquileres
data_clean[(data_clean.property_type == "store") & (data_clean.price_aprox_usd < 10000)].filter(items=["price_aprox_usd", "description"])

       price_aprox_usd                                        description
836            8412.55  Venta de Negocio  en Tolosa, La Plata116 entre...
37594          6730.04  Venta de puesto de diarios, excelente ubicaciÃ...
40173          8244.30  Fondo de comercio almacÃ©n/quiosco.En Galeria,...
40576          6231.51  CODIGO: 1834-024 ubicado en: LOCAL CENTRICO EN...
46687          8973.38  SE VENDE O SE ALQUILAN  MAQUINAS + BANCOS - BA...
48004          8412.55  Fondo de comercio : De Indumentaria Femenina. ...
51890          8412.55  26 LOTES EXCEPCIONALES EN GENERAL RODRIGUEZ.PO...
56407          7500.00  LOCALSARGENTO CABRAL 8, RAMOS MEJÃA. LOCAL DE...
56924          8412.55  Fondo de comercio : De Indumentaria Femenina. ...
58951          6231.51  CODIGO: 3122-VBB-019 ubicado en: Rondeau 201 -...
59875          4952.45  Exelente oportunidad. Venta de fondo de comerc...
63543          5608.36  Muy lindo local con renta de $ 7000vencimiento...
66969          6169.20  VENTA DE PUESTO DE DIARIOS Y REVISTAS GOYENA. ...
84347          6383.89  GuzmÃ¡n &amp; GuzmÃ¡n inmobiliaria + construct...
99066          8973.38  VENTA FONDO DE COMERCIO EN BELGRANOAl Frente: ...
99089          8973.38  VENTA FONDO DE COMERCIO EN COGHLANAl Frente: f...